spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/festival_backend_dev
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

app:
  file:
    upload-dir: uploads
    image-dir: uploads/images
    video-dir: uploads/videos
    base-url: http://localhost:8080
